version: '3.8'

services:
  medical-journal-bot:
    build: .
    container_name: medical-journal-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - medical_journal_data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  medical_journal_data:
    driver: local 