version: '3.8'

services:
  medical-journal-bot:
    build: .
    container_name: medical-journal-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 